service: lambda-testing-api
frameworkVersion: "3"
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
